"""
Task-related prompts package.
This package contains all the prompts used by the task agent system.
"""

from .task_prompts import (
    TASK_EXTRACTION_SYSTEM_PROMPT,
    TASK_JUDGMENT_SYSTEM_PROMPT,
    SUBTASK_GENERATION_SYSTEM_PROMPT,
    SUBTASK_JUDGMENT_SYSTEM_PROMPT,
    TASK_CLARIFICATION_SYSTEM_PROMPT,
    SUBTASK_DECISION_PROMPT
)

__all__ = [
    'TASK_EXTRACTION_SYSTEM_PROMPT',
    'TASK_JUDGMENT_SYSTEM_PROMPT',
    'SUBTASK_GENERATION_SYSTEM_PROMPT',
    'SUBTASK_JUDGMENT_SYSTEM_PROMPT',
    'TASK_CLARIFICATION_SYSTEM_PROMPT',
    'SUBTASK_DECISION_PROMPT'
] 